### ISSUE TITLE
[Quest] Support kill-a-unique-mob quest

### ISSUE THREAD

**Issue by Tzook** [Tzook/lul#102]
This will enable entering a room and kill a 'boss', which is only available when you have the quest.

**Comment by benk0913** [comment]
@Tzook I think all we need to add is basically 

1) the ability to set a room as "seperate instance" in content god. So the server will know to clone a new instance of a room instead of using the room's existing one. In this room, mob spawners and everything should work as same.

2) Also add the ability to have "room spawn" on spawner (Spawn a mob only if someone entered room) , it will ignore the rest of the parameters (respawn time / cap)
